apiVersion: v1
kind: Service
metadata:
  name: max-image-segmenter
spec:
  containers:
      - name: max-image-segmenter
        image: codait/max-image-segmenter
       ports:
        - containerPort: 5000 
        - port: 5000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: max-image-segmenter-web-app
  labels:
    app: max-image-segmenter-web-app
spec:
  selector:
    matchLabels:
      app: max-image-segmenter-web-app
  replicas: 1
  template:
    metadata:
      labels:
        app: max-image-segmenter-web-app
    spec:
      containers:
      - name: max-image-segmenter
        image: codait/max-image-segmenter-web-app
        ports:
        - containerPort: 3000
